apiVersion: apps/v1
kind: Deployment
metadata:
  name: championships
  labels:
    app: championships
    version: v1
spec:
  replicas: 1
  template:
    metadata:
      name: championships
      labels:
        app: championships
        version: v1
    spec:
      containers:
        - name: championships
          image: kurtis/championships:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 10
      restartPolicy: Always
  selector:
    matchLabels:
      app: championships
      version: v1