---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teams-v1
  labels:
    app: teams
    version: v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: teams
        version: v1
    spec:
      containers:
        - name: teams
          image: kurtis/teams:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /live
              port: 9000
            initialDelaySeconds: 1
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 9000
            initialDelaySeconds: 1
            periodSeconds: 10
      restartPolicy: Always
  selector:
    matchLabels:
      app: teams
      version: v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teams-v2
  labels:
    app: teams
    version: v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: teams
        version: v2
    spec:
      containers:
        - name: teams
          image: kurtis/teams:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /live
              port: 9000
            initialDelaySeconds: 1
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 9000
            initialDelaySeconds: 1
            periodSeconds: 10
      restartPolicy: Always
  selector:
    matchLabels:
      app: teams
      version: v2
