apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.apps/bets.yaml
  - deployment.apps/championships.yaml
  - deployment.apps/matches.yaml
  - deployment.apps/teams.yaml
  - service/bets.yaml
  - service/championships.yaml
  - service/matches.yaml
  - service/teams.yaml
configMapGenerator:
  - name: bets
    envs:
      - .env
