{{- $image := .Values.championships.image -}}
{{- $annotations := .Values.championships.annotations -}}
{{- $replicas := .Values.championships.replicaCount -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: championships
  labels:
    app: championships
spec:
  replicas: {{ $replicas }}
  template:
    metadata:
      name: championships
      labels:
        app: championships
    {{- if $annotations }}
      annotations:
      {{- range $key, $value := $annotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
    {{- end }}
    spec:
      containers:
        - name: championships
          image: {{ (printf "%s/championships:%s" $image.repository $image.tag) }}
          imagePullPolicy: {{ $image.pullPolicy }}
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 10
      restartPolicy: Always
  selector:
    matchLabels:
      app: championships
