{{- $image := .Values.matches.image -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: matches
  labels:
    app: matches
spec:
  replicas: 1
  template:
    metadata:
      name: matches
      labels:
        app: matches
    spec:
      containers:
        - name: matches
          image: {{ (printf "%s/matches:%s" $image.repository $image.tag) }}
          imagePullPolicy: {{ $image.pullPolicy }}
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 10
      restartPolicy: Always
  selector:
    matchLabels:
      app: matches
