{{- $image := .Values.matches.image -}}
{{- $annotations := .Values.matches.annotations -}}
{{- $replicas := .Values.matches.replicaCount -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: matches
  labels:
    app: matches
spec:
  replicas: {{ $replicas }}
  template:
    metadata:
      name: matches
      labels:
        app: matches
    {{- if $annotations }}
      annotations:
      {{- range $key, $value := $annotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
    {{- end }}
    spec:
      containers:
        - name: matches
          image: {{ (printf "%s/matches:%s" $image.repository $image.tag) }}
          imagePullPolicy: {{ $image.pullPolicy }}
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 10
      restartPolicy: Always
  selector:
    matchLabels:
      app: matches
